import React, { useRef } from 'react'
import { useGLTF, OrbitControls } from '@react-three/drei'
import { Canvas, useFrame } from '@react-three/fiber'
import { DoubleSide } from 'three'
import { memo } from 'react';


function Scene(props) {

    const ref = useRef()

    useFrame(() => {
        ref.current.rotation.y -= 0.001
    })

    const { nodes, materials } = useGLTF('/25042_Perseverance.glb')
    return (
        <>
            <group {...props} dispose={null} scale={1} position={[0, -1, 0]} ref={ref}>
                <group position={[-0.02, 1.156, 0.082]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube025.geometry}
                        material={materials.mars_2020_03}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube025_1.geometry}
                        material={materials.mars_2020_01}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube025_2.geometry}
                        material={materials.mars_2020_04}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube025_3.geometry}
                        material={materials.mars_2020_02}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube025_4.geometry}
                        material={materials.paint_white_base}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube025_5.geometry}
                        material={materials.mars_2020_04_aluminum_r}
                    />
                </group>
                <group position={[-0.077, 0.724, 0.972]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={
                            nodes['10461516-101_A3-FRONT_HAZCAM_LENS_COVER_MOUNTING_BRACKET_59014'].geometry
                        }
                        material={materials.aluminum_black}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={
                            nodes['10461516-101_A3-FRONT_HAZCAM_LENS_COVER_MOUNTING_BRACKET_59014_1'].geometry
                        }
                        material={materials.paint_white_base}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={
                            nodes['10461516-101_A3-FRONT_HAZCAM_LENS_COVER_MOUNTING_BRACKET_59014_2'].geometry
                        }
                        material={materials.mars_2020_05}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={
                            nodes['10461516-101_A3-FRONT_HAZCAM_LENS_COVER_MOUNTING_BRACKET_59014_3'].geometry
                        }
                        material={materials.aluminum}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={
                            nodes['10461516-101_A3-FRONT_HAZCAM_LENS_COVER_MOUNTING_BRACKET_59014_4'].geometry
                        }
                        material={materials.spring}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={
                            nodes['10461516-101_A3-FRONT_HAZCAM_LENS_COVER_MOUNTING_BRACKET_59014_5'].geometry
                        }
                        material={materials.mars_2020_06_brass2}
                    />
                </group>
                <group position={[0.088, 0.683, 0.982]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={
                            nodes['10461516-101_A3-FRONT_HAZCAM_LENS_COVER_MOUNTING_BRACKET_59000'].geometry
                        }
                        material={materials['aluminum_black.001']}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={
                            nodes['10461516-101_A3-FRONT_HAZCAM_LENS_COVER_MOUNTING_BRACKET_59000_1'].geometry
                        }
                        material={materials['mars_2020_04.001']}
                    />
                </group>
                <group position={[0.472, 0.779, -1.142]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes['10461523-101_A-REAR_-Y_HAZCAM_BRACKET_12976004'].geometry}
                        material={materials.aluminum_black}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes['10461523-101_A-REAR_-Y_HAZCAM_BRACKET_12976004_1'].geometry}
                        material={materials.mars_2020_06_brass2}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes['10461523-101_A-REAR_-Y_HAZCAM_BRACKET_12976004_2'].geometry}
                        material={materials.grey_brushed}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes['10461523-101_A-REAR_-Y_HAZCAM_BRACKET_12976004_3'].geometry}
                        material={materials.aluminum}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes['10461523-101_A-REAR_-Y_HAZCAM_BRACKET_12976004_4'].geometry}
                        material={materials.paint_white_base}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes['10461523-101_A-REAR_-Y_HAZCAM_BRACKET_12976004_5'].geometry}
                        material={materials.mars_2020_05}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes['10461523-101_A-REAR_-Y_HAZCAM_BRACKET_12976004_6'].geometry}
                        material={materials.spring}
                    />
                </group>
                <group position={[0.513, 0.815, -1.223]} rotation={[-Math.PI / 4, -0.385, 0]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube001.geometry}
                        material={materials.aluminum_black}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube001_1.geometry}
                        material={materials.mars_2020_04}
                    />
                </group>
                <group position={[-0.513, 0.815, -1.223]} rotation={[2.356, -0.385, -Math.PI]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube013.geometry}
                        material={materials.aluminum_black}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube013_1.geometry}
                        material={materials.mars_2020_04}
                    />
                </group>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.hazcams_rear_wiring.geometry}
                    material={materials.grey_brushed}
                    position={[0.472, 0.779, -1.142]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.microphones.geometry}
                    material={materials.grey_brushed}
                    position={[0.61, 1.014, -0.3]}
                />
                <group position={[0, 0.264, -0.035]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes['10272356-101_E-HORIZONTAL_SWINGARM_25223001'].geometry}
                        material={materials.aluminum_black}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes['10272356-101_E-HORIZONTAL_SWINGARM_25223001_1'].geometry}
                        material={materials.aluminum}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes['10272356-101_E-HORIZONTAL_SWINGARM_25223001_2'].geometry}
                        material={materials.hub}
                    />
                </group>
                <group position={[0, 0.711, -0.035]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes['10272356-101_E-HORIZONTAL_SWINGARM_25223002'].geometry}
                        material={materials.gunmetal}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes['10272356-101_E-HORIZONTAL_SWINGARM_25223002_1'].geometry}
                        material={materials.mars_2020_05_gunmetal}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes['10272356-101_E-HORIZONTAL_SWINGARM_25223002_2'].geometry}
                        material={materials.gunmetal_dark}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes['10272356-101_E-HORIZONTAL_SWINGARM_25223002_3'].geometry}
                        material={materials.aluminum}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes['10272356-101_E-HORIZONTAL_SWINGARM_25223002_4'].geometry}
                        material={materials.gray_krinkle}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes['10272356-101_E-HORIZONTAL_SWINGARM_25223002_5'].geometry}
                        material={materials.mars_2020_05}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes['10272356-101_E-HORIZONTAL_SWINGARM_25223002_6'].geometry}
                        material={materials.mars_2020_gunmetal_dark}
                    />
                </group>
                <group position={[-0.013, 0.961, 1.12]} rotation={[-Math.PI, 0, 0]} scale={0.034}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder005.geometry}
                        material={materials.gunmetal}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder005_1.geometry}
                        material={materials.gunmetal_dark}
                    />
                </group>
                <group position={[0.451, 0.915, 1.176]} rotation={[-Math.PI, -1.571, 0]} scale={0.034}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder013.geometry}
                        material={materials.gunmetal_dark}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder013_1.geometry}
                        material={materials.gunmetal}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder013_2.geometry}
                        material={materials.paint_white_base}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder013_3.geometry}
                        material={materials.foil_orange}
                    />
                    <group position={[-4.955, 2.748, 2.321]} rotation={[0, 0, -0.283]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder014.geometry}
                            material={materials.paint_white_base}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder014_1.geometry}
                            material={materials.gunmetal_dark}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder014_2.geometry}
                            material={materials.mars_2020_07}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder014_3.geometry}
                            material={materials.gunmetal}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder014_4.geometry}
                            material={materials.arm_graphics}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder014_5.geometry}
                            material={materials.mars_2020_02_n}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder014_6.geometry}
                            material={materials.bronze}
                        />
                        <group position={[-23.488, -6.823, 0.652]} rotation={[0, 0, -1.256]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder041.geometry}
                                material={materials.gunmetal_dark}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder041_1.geometry}
                                material={materials.paint_white_base}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder041_2.geometry}
                                material={materials.mars_2020_07}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder041_3.geometry}
                                material={materials.gunmetal}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder041_4.geometry}
                                material={materials.foil_orange}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder041_5.geometry}
                                material={materials.arm_graphics}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder041_6.geometry}
                                material={materials.mars_2020_02_n}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder041_7.geometry}
                                material={materials.bronze}
                            />
                            <group position={[22.473, -0.723, 0.573]} rotation={[0, 0, 1.539]}>
                                <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Cylinder018.geometry}
                                    material={materials.gunmetal}
                                />
                                <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Cylinder018_1.geometry}
                                    material={materials.gunmetal_dark}
                                />
                                <group
                                    position={[5.245, -4.551, 1.802]}
                                    rotation={[-3.136, -1.413, 0.005]}
                                    scale={29.848}>
                                    <mesh
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Cylinder015.geometry}
                                        material={materials.gunmetal}
                                    />
                                    <mesh
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Cylinder015_1.geometry}
                                        material={materials.gunmetal_dark}
                                    />
                                    <mesh
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Cylinder015_2.geometry}
                                        material={materials.Material}
                                    />
                                    <mesh
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Cylinder015_3.geometry}
                                        material={materials.foil_orange}
                                    />
                                    <mesh
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Cylinder015_4.geometry}
                                        material={materials.aluminum}
                                    />
                                    <mesh
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Cylinder015_5.geometry}
                                        material={materials.paint_white_base}
                                    />
                                    <mesh
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Cylinder015_6.geometry}
                                        material={materials.bronze}
                                    />
                                    <mesh
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Cylinder015_7.geometry}
                                        material={materials.mars_2020_07}
                                    />
                                    <mesh
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Cylinder015_8.geometry}
                                        material={materials.mars_2020_06}
                                    />
                                    <mesh
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Cylinder015_9.geometry}
                                        material={materials.arm_graphics}
                                    />
                                    <group position={[-0.034, 0.176, 0.231]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cylinder012.geometry}
                                            material={materials.aluminum}
                                        />
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cylinder012_1.geometry}
                                            material={materials.gunmetal}
                                        />
                                    </group>
                                    <group position={[0.289, 0.168, 0.169]} rotation={[-Math.PI, 0.017, -Math.PI]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cylinder032.geometry}
                                            material={materials.gunmetal}
                                        />
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cylinder032_1.geometry}
                                            material={materials.glass_2}
                                        />
                                    </group>
                                    <group position={[0.326, 0.219, -0.086]} rotation={[-Math.PI, 0.017, -Math.PI]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cylinder031.geometry}
                                            material={materials.gunmetal}
                                        />
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cylinder031_1.geometry}
                                            material={materials.glass_2}
                                        />
                                    </group>
                                    <mesh
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.hinge.geometry}
                                        material={materials.transparent}
                                        position={[-0.317, 0.142, -0.041]}
                                        rotation={[2.486, -1.374, 0.925]}>
                                        <group rotation={[-1.415, -0.019, -1.689]}>
                                            <mesh
                                                castShadow
                                                receiveShadow
                                                geometry={nodes.Cylinder003.geometry}
                                                material={materials.mars_2020_05}
                                            />
                                            <mesh
                                                castShadow
                                                receiveShadow
                                                geometry={nodes.Cylinder003_1.geometry}
                                                material={materials['glass lens']}
                                            />
                                        </group>
                                    </mesh>
                                    <group position={[-0.243, 0.168, -0.038]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cylinder001.geometry}
                                            material={materials.paint_white_base}
                                        />
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cylinder001_1.geometry}
                                            material={materials.mars_2020_05}
                                        />
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cylinder001_2.geometry}
                                            material={materials.glass_2}
                                        />
                                    </group>
                                    <group position={[0.234, 0.183, 0.049]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cylinder008.geometry}
                                            material={materials.iron}
                                        />
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cylinder008_1.geometry}
                                            material={materials.gunmetal_dark}
                                        />
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cylinder008_2.geometry}
                                            material={materials.glass_2}
                                        />
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cylinder008_3.geometry}
                                            material={materials.gunmetal}
                                        />
                                    </group>
                                    <group position={[0.234, 0.183, 0.049]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cylinder021.geometry}
                                            material={materials.gunmetal}
                                        />
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cylinder021_1.geometry}
                                            material={materials.gunmetal_dark}
                                        />
                                    </group>
                                    <mesh
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.turret_obj006.geometry}
                                        material={materials.gunmetal_dark}
                                        position={[0.234, 0.183, 0.049]}
                                    />
                                    <group position={[0.234, 0.183, 0.049]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cylinder023.geometry}
                                            material={materials.gunmetal_dark}
                                        />
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cylinder023_1.geometry}
                                            material={materials.aluminum}
                                        />
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cylinder023_2.geometry}
                                            material={materials.gunmetal}
                                        />
                                    </group>
                                    <group position={[0.307, 0.194, -0.062]}>
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cylinder009.geometry}
                                            material={materials.gunmetal_dark}
                                        />
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cylinder009_1.geometry}
                                            material={materials.iron}
                                        />
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cylinder009_2.geometry}
                                            material={materials.glass_2}
                                        />
                                        <mesh
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cylinder009_3.geometry}
                                            material={materials.gunmetal}
                                        />
                                    </group>
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
                <group
                    position={[-0.021, 1.131, 0.809]}
                    rotation={[2.713, -0.769, 0.429]}
                    scale={[0.137, 0.251, 0.137]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder054.geometry}
                        material={materials.mars_2020_05}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder054_1.geometry}
                        material={materials.mars_2020_05_aluminum}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder054_2.geometry}
                        material={materials.mars_2020_05_brass}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder054_3.geometry}
                        material={materials.gunmetal}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder054_4.geometry}
                        material={materials.mars_2020_05_gunmetal}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder054_5.geometry}
                        material={materials.aluminum}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder054_6.geometry}
                        material={materials.mars_2020_01}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder054_7.geometry}
                        material={materials.arm_graphics}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder054_8.geometry}
                        material={materials.spring}
                    />
                </group>
                <group position={[0, 1.156, -1.249]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube009.geometry}
                        material={materials.mars_2020_05}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube009_1.geometry}
                        material={materials.mars_2020_05_cooling_lines}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube009_2.geometry}
                        material={materials.mars_2020_04}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube009_3.geometry}
                        material={materials.gunmetal}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube009_4.geometry}
                        material={materials.mars_2020_06_brass2}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube009_5.geometry}
                        material={materials.copper}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube009_6.geometry}
                        material={materials.mars_2020_03}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube009_7.geometry}
                        material={materials['array gold trim']}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube009_8.geometry}
                        material={materials.gold}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube009_9.geometry}
                        material={materials.aluminum_black}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube009_10.geometry}
                        material={materials.aluminum}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube009_11.geometry}
                        material={materials.paint_white_base}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube009_12.geometry}
                        material={materials.gunmetal_dark}
                    />
                </group>
                <group position={[-0.505, 1.64, -1.083]} scale={[0.083, 0.093, 0.083]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder.geometry}
                        material={materials.black_krinkle}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder_1.geometry}
                        material={materials.gunmetal_dark}
                    />
                </group>
                <group position={[0.418, 1.284, -0.394]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes['10253070-104_B8-MSL_HGA_DISH_INTFC_115678013'].geometry}
                        material={materials.aluminum}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes['10253070-104_B8-MSL_HGA_DISH_INTFC_115678013_1'].geometry}
                        material={materials.mars_2020_01}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes['10253070-104_B8-MSL_HGA_DISH_INTFC_115678013_2'].geometry}
                        material={materials.brass}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes['10253070-104_B8-MSL_HGA_DISH_INTFC_115678013_3'].geometry}
                        material={materials.gunmetal}
                    />
                </group>
                <group position={[0.495, 1.509, -0.939]} rotation={[-Math.PI, 0, 0]} scale={0.001}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes['10450513-101_B-WAVEGUIDE,_RIGID,_RECTANGULAR_50248000'].geometry}
                        material={materials.mars_2020_05}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes['10450513-101_B-WAVEGUIDE,_RIGID,_RECTANGULAR_50248000_1'].geometry}
                        material={materials.mars_2020_06_brass2}
                    />
                </group>
                <group position={[0.611, 0.712, 0.831]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube026.geometry}
                        material={materials.aluminum}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube026_1.geometry}
                        material={materials.gunmetal}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube026_2.geometry}
                        material={materials.grey_brushed}
                    />
                </group>
                <group position={[-0.611, 0.715, 0.831]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube027.geometry}
                        material={materials.aluminum}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube027_1.geometry}
                        material={materials.gunmetal}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube027_2.geometry}
                        material={materials.grey_brushed}
                    />
                </group>
                <group position={[-0.02, 1.156, 0.082]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube029.geometry}
                        material={materials.aluminum}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube029_1.geometry}
                        material={materials.paint_white_base}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube029_2.geometry}
                        material={materials.mars_2020_05}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube029_3.geometry}
                        material={materials.gunmetal_dark}
                    />
                </group>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.RIMFAX.geometry}
                    material={materials.mars_2020_01}
                    position={[0, 0.779, -1.056]}
                />
                <group position={[0, 1.46, -0.906]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube024.geometry}
                        material={materials.mars_2020_04}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube024_1.geometry}
                        material={materials.arm_graphics}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube024_2.geometry}
                        material={materials.grey_brushed}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube024_3.geometry}
                        material={materials.aluminum}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube024_4.geometry}
                        material={materials.glass_2}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube024_5.geometry}
                        material={materials.nameplate}
                    />
                </group>
                <group position={[-0.626, 1.245, 0.606]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube008.geometry}
                        material={materials.mars_2020_01_n}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube008_1.geometry}
                        material={materials.gunmetal}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube008_2.geometry}
                        material={materials.paint_white_base}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube008_3.geometry}
                        material={materials.mars_2020_06_brass2}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube008_4.geometry}
                        material={materials.aluminum}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube008_5.geometry}
                        material={materials.mars_2020_02_n}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube008_6.geometry}
                        material={materials.bronze}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube008_7.geometry}
                        material={materials.blades}
                    />
                    <group position={[-0.038, 0.356, 0.13]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cube022.geometry}
                            material={materials.paint_white_base}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cube022_1.geometry}
                            material={materials.mars_2020_03}
                        />
                    </group>
                    <group position={[0.073, 0.255, 0.08]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cube023.geometry}
                            material={materials.paint_white_base}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cube023_1.geometry}
                            material={materials.bronze}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cube023_2.geometry}
                            material={materials.aluminum}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cube023_3.geometry}
                            material={materials.mars_2020_01_n}
                        />
                    </group>
                    <group position={[-0.136, 0.372, -0.061]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder002.geometry}
                            material={materials['aluminum.003']}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder002_1.geometry}
                            material={materials['mars_2020_03.002']}
                        />
                    </group>
                    <group position={[0.07, 0.548, 0.107]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder016.geometry}
                            material={materials.paint_white_base}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder016_1.geometry}
                            material={materials.gunmetal}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder016_2.geometry}
                            material={materials.mars_2020_06_brass2}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder016_3.geometry}
                            material={materials.mars_2020_01_n}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder016_4.geometry}
                            material={materials.bronze}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder016_5.geometry}
                            material={materials.gunmetal_dark}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder016_6.geometry}
                            material={materials['aluminum.001']}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder016_7.geometry}
                            material={materials.mars_2020_02_n}
                        />
                    </group>
                </group>
                <group position={[-0.522, 1.922, 0.713]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes['10453412-101_B_3961624048'].geometry}
                        material={materials.mars_2020_02}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes['10453412-101_B_3961624048_1'].geometry}
                        material={materials.mars_2020_03}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes['10453412-101_B_3961624048_2'].geometry}
                        material={materials.paint_white_base}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes['10453412-101_B_3961624048_3'].geometry}
                        material={materials.gunmetal}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes['10453412-101_B_3961624048_4'].geometry}
                        material={materials.bronze}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes['10453412-101_B_3961624048_5'].geometry}
                        material={materials.mars_2020_06_brass2}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes['10453412-101_B_3961624048_6'].geometry}
                        material={materials.mars_2020_01_n}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes['10453412-101_B_3961624048_7'].geometry}
                        material={materials.aluminum_black}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes['10453412-101_B_3961624048_8'].geometry}
                        material={materials.mars_2020_02_n}
                    />
                    <group position={[0.078, 0.214, 0.068]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['10453412-101_B_3961624003'].geometry}
                            material={materials.gunmetal}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['10453412-101_B_3961624003_1'].geometry}
                            material={materials.mars_2020_02}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['10453412-101_B_3961624003_2'].geometry}
                            material={materials.paint_white_base}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['10453412-101_B_3961624003_3'].geometry}
                            material={materials.glass_2}
                        />
                    </group>
                    <group position={[-0.032, 0.135, 0.002]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['10453412-101_B_3961624002'].geometry}
                            material={materials.mars_2020_02}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['10453412-101_B_3961624002_1'].geometry}
                            material={materials.paint_white_base}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['10453412-101_B_3961624002_2'].geometry}
                            material={materials.mars_2020_06_brass2}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['10453412-101_B_3961624002_3'].geometry}
                            material={materials.aluminum_black}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['10453412-101_B_3961624002_4'].geometry}
                            material={materials.gunmetal}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['10453412-101_B_3961624002_5'].geometry}
                            material={materials.glass_2}
                        />
                    </group>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.microphones001.geometry}
                        material={materials.grey_brushed}
                        position={[0.015, 0.154, 0.124]}
                    />
                    <group position={[-0.033, 0.05, 0.053]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['10453412-101_B_3961624001'].geometry}
                            material={materials.paint_white_base}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['10453412-101_B_3961624001_1'].geometry}
                            material={materials.mars_2020_02}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['10453412-101_B_3961624001_2'].geometry}
                            material={materials.aluminum_black}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['10453412-101_B_3961624001_3'].geometry}
                            material={materials.mars_2020_05}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['10453412-101_B_3961624001_4'].geometry}
                            material={materials.glass_2}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['10453412-101_B_3961624001_5'].geometry}
                            material={materials.aluminum}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['10453412-101_B_3961624001_6'].geometry}
                            material={materials.mars_2020_06_brass2}
                        />
                    </group>
                </group>
                <group position={[-0.563, 1.211, 0.72]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes['10453412-101_B_3961624036'].geometry}
                        material={materials.paint_white_base}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes['10453412-101_B_3961624036_1'].geometry}
                        material={materials.gunmetal}
                    />
                </group>
                <group position={[-0.626, 1.245, 0.606]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube002.geometry}
                        material={materials.bronze}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube002_1.geometry}
                        material={materials.mars_2020_02_n}
                    />
                </group>
                <group position={[-0.388, 1.33, -0.603]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube028.geometry}
                        material={materials.aluminum}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube028_1.geometry}
                        material={materials.gunmetal}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube028_2.geometry}
                        material={materials['glass lens']}
                    />
                </group>
                <group position={[0.647, 0.779, 0.668]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube003.geometry}
                        material={materials.aluminum}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube003_1.geometry}
                        material={materials.paint_white_base}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube003_2.geometry}
                        material={materials.mars_2020_05}
                    />
                </group>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.arm_01_joint.geometry}
                    material={materials.aluminum}
                    position={[-0.414, 0.664, -0.232]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.arm_01_pivot.geometry}
                        material={materials.transparent}
                        position={[-0.007, -0.003, 0.042]}
                        rotation={[Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.arm_01.geometry}
                            material={materials.gunmetal}
                            position={[-0.068, -0.048, 0.005]}
                            rotation={[Math.PI / 2, Math.PI / 2, 0]}
                            scale={0.001}
                        />
                    </mesh>
                </mesh>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.arm_02_joint.geometry}
                    material={materials.aluminum}
                    position={[0.019, 0.702, -0.259]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.arm_02_pivot.geometry}
                        material={materials.transparent}
                        position={[0, -0.002, 0.112]}
                        rotation={[Math.PI / 2, 0, Math.PI]}>
                        <group position={[-0.083, 0.09, 0.01]} rotation={[Math.PI / 2, 0, -Math.PI]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={
                                    nodes['10463723-1_6-MHDS_BELLY_PAN_A1-MIA,_MHDS_BELLY_PAN_655754007'].geometry
                                }
                                material={materials.gunmetal}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={
                                    nodes['10463723-1_6-MHDS_BELLY_PAN_A1-MIA,_MHDS_BELLY_PAN_655754007_1'].geometry
                                }
                                material={materials.iron}
                            />
                        </group>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.arm_02001.geometry}
                            material={materials.iron}
                            position={[-0.083, 0.09, 0.01]}
                            rotation={[Math.PI / 2, 0, -Math.PI]}
                        />
                    </mesh>
                </mesh>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.pan_end_cover.geometry}
                    material={materials.aluminum}
                    position={[-0.191, 0.673, -0.84]}
                />
                <group position={[-0.02, 1.156, 0.082]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube006.geometry}
                        material={materials.mars_2020_04}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube006_1.geometry}
                        material={materials.mars_2020_01}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube006_2.geometry}
                        material={materials.mars_2020_02}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube006_3.geometry}
                        material={materials.mars_2020_03}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube006_4.geometry}
                        material={materials.mars_2020_06_n}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube006_5.geometry}
                        material={materials.aluminum}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube006_6.geometry}
                        material={materials.gunmetal_dark}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube006_7.geometry}
                        material={materials.paint_white_base}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube006_8.geometry}
                        material={materials.mars_2020_06_brass2}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube006_9.geometry}
                        material={materials.brass}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube006_10.geometry}
                        material={materials.grey_brushed}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube006_11.geometry}
                        material={materials.spring}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube006_12.geometry}
                        material={materials.mars_2020_05}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube006_13.geometry}
                        material={materials.gunmetal}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube006_14.geometry}
                        material={materials.aluminum_black}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube006_15.geometry}
                        material={materials.mars_2020_04_aluminum_r}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube006_16.geometry}
                        material={materials['aluminum_black.001']}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube006_17.geometry}
                        material={materials.blades}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube006_18.geometry}
                        material={materials.covidPlaque}
                    />
                </group>
                <group position={[-0.488, 0.88, 1.227]} rotation={[-Math.PI, 1.571, 0]} scale={0.001}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={
                            nodes['CEK_M2020_BLANK_SUPPORT_STRUTS_05_A1-BLANK_SUPPORT_STRUTS_1000'].geometry
                        }
                        material={materials.sample_handling_door}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={
                            nodes['CEK_M2020_BLANK_SUPPORT_STRUTS_05_A1-BLANK_SUPPORT_STRUTS_1000_1'].geometry
                        }
                        material={materials.gunmetal}
                    />
                </group>
                <group position={[-0.02, 1.156, 0.082]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube005.geometry}
                        material={materials.gunmetal}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube005_1.geometry}
                        material={materials.gunmetal_dark}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube005_2.geometry}
                        material={materials.mars_2020_01}
                    />
                </group>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.calibration_target_bracket.geometry}
                    material={materials.gunmetal_dark}
                    position={[-0.02, 1.156, 0.082]}
                />
                <group position={[-0.02, 1.156, 0.082]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube021.geometry}
                        material={materials.mars_2020_06}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube021_1.geometry}
                        material={materials.gunmetal_dark}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube021_2.geometry}
                        material={materials.aluminum}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube021_3.geometry}
                        material={materials.mars_2020_05}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube021_4.geometry}
                        material={materials.mars_2020_01}
                    />
                </group>
                <group position={[0.538, 1.145, 0.872]} rotation={[-Math.PI, 0, 0]} scale={0.034}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder006.geometry}
                        material={materials.mars_2020_07}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder006_1.geometry}
                        material={materials.paint_white_base}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder006_2.geometry}
                        material={materials.gunmetal}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder006_3.geometry}
                        material={materials.mars_2020_02_n}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder006_4.geometry}
                        material={materials.bronze}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder006_5.geometry}
                        material={materials.mars_2020_02}
                    />
                </group>
            </group>
            <mesh scale={5} position={[0, -1, 0]} rotation={[Math.PI * -0.5, 0, 0]} receiveShadow>
                <planeGeometry args={[1, 1]} />
                <meshStandardMaterial color={"white"} side={DoubleSide} />
            </mesh>
        </>
    )
}

const Perseverance = memo(function Perseverance(props) {

    return (
        <Canvas camera={{ fov: 80, position: [0, 0, 5] }} shadows style={{ height: "400px" }}>
            <OrbitControls minDistance={4.0} maxDistance={5.0} />
            <ambientLight intensity={1} />
            <directionalLight intensity={5} position={[0, 2, 0]} color={"white"} castShadow />
            <directionalLight intensity={5} position={[0, 0, 2]} color={"#B0845B"} castShadow />
            <directionalLight intensity={5} position={[-2, 0, 0]} color={"#B0845B"} castShadow />
            <directionalLight intensity={5} position={[2, 0, 0]} color={"#B0845B"} castShadow />
            <Scene props={props} />

        </Canvas>

    )
})

useGLTF.preload('/25042_Perseverance.glb')

export default Perseverance