name: Notify on Issue Close

on:
  issues:
    types: [closed]

jobs:
  notify-on-close:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Issue Creator
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue } = context.payload.issue;
            const { login } = issue.user.login;
            const { number } = issue.number;
            const message = `Hello @${login}! Your issue #${number} has been closed. Thank you for your contribution!`;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: number,
              body: message
            });
