name: MK Docs

on:
  push:
    branches:
      - main
    tags:
      - "*"
      - "Documentation-*"
  pull_request_target:

jobs:
  build:
    name: Build MkDocs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('mkdocs/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r mkdocs/requirements.txt

      - name: Build MK Docs project
        run: mkdocs build -f mkdocs/mkdocs.yml

      - name: Upload MK Docs build files
        uses: actions/upload-artifact@v4
        with:
          name: mkdocs-files
          path: ./mkdocs/site

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/tags/Documentation-')
    
    steps:
      - name: Download MkDocs artifact
        uses: actions/download-artifact@v4
        with:
          name: mkdocs-files
          path: ./mkdocs/site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ./mkdocs/site
